// Ambient charting client: record consultation audio, send it to the FastAPI
// backend (Groq Whisper + Llama), and get structured notes back. Everything
// degrades gracefully so the UI never dead-ends.
import { jsPDF } from 'jspdf'

// In dev → local FastAPI. In production (Vercel) → same-origin, where /api/* is
// routed to the backend service by vercel.json. Override with VITE_CHART_API_URL.
const BACKEND_URL = import.meta.env.VITE_CHART_API_URL ?? (import.meta.env.DEV ? 'http://localhost:8000' : '')

// A canned result used when the backend / mic is unavailable, so the flow is
// always demoable.
const FALLBACK_NOTE = {
  summary: 'Offline sample — start the charting backend (backend/README.md) for real AI notes.',
  symptoms: ['Right knee pain after running', 'Mild swelling for 3 days'],
  prescriptions: ['Ibuprofen 400mg twice daily with food'],
  actions: ['RICE protocol', 'MRI if no improvement in 1 week', 'Physiotherapy referral'],
  transcript: '',
  engine: 'offline',
}

// Start recording from the microphone. Returns a controller with stop().
export async function startRecording() {
  if (!navigator.mediaDevices?.getUserMedia || typeof MediaRecorder === 'undefined') {
    throw new Error('Recording not supported in this browser')
  }
  const stream = await navigator.mediaDevices.getUserMedia({ audio: true })
  const chunks = []
  const rec = new MediaRecorder(stream)
  rec.ondataavailable = (e) => e.data.size && chunks.push(e.data)
  rec.start()

  return {
    stop: () =>
      new Promise((resolve) => {
        rec.onstop = () => {
          stream.getTracks().forEach((t) => t.stop())
          resolve(new Blob(chunks, { type: rec.mimeType || 'audio/webm' }))
        }
        rec.stop()
      }),
  }
}

// Send audio (and/or a transcript) to the backend for structuring.
export async function generateNotes({ audioBlob, transcript = '' }) {
  try {
    const form = new FormData()
    if (audioBlob) form.append('audio', audioBlob, 'consult.webm')
    if (transcript) form.append('transcript', transcript)

    const res = await fetch(`${BACKEND_URL}/api/chart`, { method: 'POST', body: form })
    if (!res.ok) throw new Error(`Backend responded ${res.status}`)
    return await res.json()
  } catch (e) {
    console.warn('charting backend unavailable, using fallback:', e.message)
    return { ...FALLBACK_NOTE, transcript }
  }
}

// Build a branded PDF of the consultation notes and trigger a download.
export function downloadNotesPDF(patient, notes) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const M = 48
  let y = M

  doc.setFillColor(6, 95, 70)
  doc.rect(0, 0, 595, 8, 'F')

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(20)
  doc.setTextColor(15, 23, 42)
  doc.text('Sporting Ethos', M, (y += 24))
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(11)
  doc.setTextColor(100, 116, 139)
  doc.text('Consultation Summary', M, (y += 18))

  doc.setDrawColor(226, 232, 240)
  doc.line(M, (y += 12), 595 - M, y)

  doc.setTextColor(15, 23, 42)
  doc.setFontSize(12)
  doc.text(`Patient: ${patient.name}`, M, (y += 26))
  doc.text(`Appointment: ${patient.appointment_id || 'walk-in'}`, M, (y += 18))
  doc.text(`Date: ${new Date(patient.check_in_time).toLocaleString()}`, M, (y += 18))

  const section = (title, items) => {
    y += 24
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(13)
    doc.setTextColor(6, 95, 70)
    doc.text(title, M, y)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(11)
    doc.setTextColor(30, 41, 59)
    const list = items && items.length ? items : ['—']
    list.forEach((it) => {
      y += 17
      const lines = doc.splitTextToSize(`•  ${it}`, 595 - M * 2)
      doc.text(lines, M, y)
      y += (lines.length - 1) * 14
    })
  }

  if (notes.summary) {
    y += 24
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(13)
    doc.setTextColor(6, 95, 70)
    doc.text('Summary', M, y)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(11)
    doc.setTextColor(30, 41, 59)
    const lines = doc.splitTextToSize(notes.summary, 595 - M * 2)
    doc.text(lines, M, (y += 17))
    y += (lines.length - 1) * 14
  }
  section('Symptoms', notes.symptoms)
  section('Prescriptions', notes.prescriptions)
  section('Actions & Follow-up', notes.actions)

  doc.setFontSize(9)
  doc.setTextColor(148, 163, 184)
  doc.text(
    `Generated by Sporting Ethos ambient charting${notes.engine ? ` · ${notes.engine}` : ''}. Review before clinical use.`,
    M,
    800
  )

  doc.save(`consultation-${patient.name.replace(/\s+/g, '-').toLowerCase()}.pdf`)
}
